package data.scripts.world.systems;

import com.fs.starfarer.api.Global;
import com.fs.starfarer.api.campaign.PlanetAPI;
import com.fs.starfarer.api.campaign.SectorAPI;
import com.fs.starfarer.api.campaign.StarSystemAPI;
import com.fs.starfarer.api.impl.campaign.ids.Factions;
import com.fs.starfarer.api.impl.campaign.procgen.NebulaEditor;
import com.fs.starfarer.api.impl.campaign.procgen.ProcgenUsedNames;
import com.fs.starfarer.api.impl.campaign.procgen.StarAge;
import com.fs.starfarer.api.impl.campaign.procgen.StarSystemGenerator;
import com.fs.starfarer.api.impl.campaign.terrain.HyperspaceTerrainPlugin;
import com.fs.starfarer.api.util.Misc;
import data.scripts.HyperionModDependencies;
import data.scripts.world.procgen.HS_AddStuffs;
import data.scripts.world.procgen.HS_AutoGenerateFactions;
import data.scripts.world.procgen.HS_Randomizer;
import data.scripts.world.procgen.variables.STAR_TYPES;
import java.awt.Color;

/**
 *
 * @author NinjaSiren
 */
public class HS_Klat {

    // Sets a random star type if Unknown Skies is enabled
    private String star_type() {
        int randomValue = new HS_Randomizer().intRand(0, 1);
        if(new HyperionModDependencies().isUnknownSkies()) {
            switch (randomValue) {
                case 1:
                    return new STAR_TYPES().BLUE_GIANT;
                default:
                    return new STAR_TYPES().BLUE_GIANT_US;
            }
        } else {
            return new STAR_TYPES().BLUE_GIANT;
        }
    }
    
    public void generate(SectorAPI sector) {
        
        // Add star system
        StarSystemAPI system = sector.createStarSystem("Klat");
        system.getLocation().set(-9750, 24500);
        system.setAge(StarAge.ANY);
        system.setBackgroundTextureFilename("graphics/backgrounds/background" + 
                new HS_RandSysBG().rand_bg() + ".jpg");
        ProcgenUsedNames.notifyUsed("Klat");
        
        // Initialize star variables
        int starSize = new HS_Randomizer().intRand(1100, 1300);
        
        // Add stars, Klat
        PlanetAPI klat = system.initStar(
                    "hs_klat", // unique id for this star
                    star_type(),  // id in planets.json
                    starSize,           // radius (in pixels at default zoom)
                    starSize * 1.5f,            // corona radius, from star edge
                    2.5f,             // solar wind burn level
                    0.7f,           // flare probability
                    2.2f);          // CR loss multipiers
        
        klat.setCustomDescriptionId("hs_star_klat"); 
        klat.setName("Klat");
        
        // Other system automation stuff
        system.setStar(klat);
        system.setHasSystemwideNebula(true);        
        
        // Sets whole system lighting color (R, G, B)
        system.setLightColor(new Color(255,255,255,255));
        klat.getSpec().setGlowTexture(Global.getSettings().getSpriteName("hab_glows", "banded"));
        klat.getSpec().setGlowColor(new Color(0, 142, 253, 128));
        klat.getSpec().setAtmosphereThickness(0.5f);
        klat.applySpecChanges();
        
        // Randomly generates planets
        StarSystemGenerator.addOrbitingEntities(
                system, // System
                klat, // Star
                system.getAge(), // Sets the potential entities added depending on system age
                10, new HS_Randomizer().intRand(10, 20), // Min-Max entities to add
                starSize * new HS_Randomizer().floatRand(1.75f, 2f), // Radius to start at
                1, // Naming offset
                false, // Custom or system based names
                true); // Should habitables appear
        
        // Randomly generates stable locations
        StarSystemGenerator.addStableLocations(system, new HS_Randomizer().intRand(1, 3));
        
        // Automatically generates random factions in the system based on the values you added
        new HS_AutoGenerateFactions().generateFactions(
                system, // The system that will have the auto-generated planets
                klat, // The star that the planets will orbit on
                "HS_Corporation_Separatist", // Faction ID of the first faction
                Factions.REMNANTS, // Faction ID of the second faction
                0.6, // The percentage of factionA appearing vs factionB on the system, min=0 max=1
                true, // Do we generate factions
                false, // Do we generate stations
                true); // Do we generate an abandoned station
        
        // Add jump points on habitable or working colonies
        new HS_AddStuffs().generateJumpPoints(system, klat);
        
        // Autogenerated jump points
        system.autogenerateHyperspaceJumpPoints(true, true);
        
        // Cleaning the hyperspace
        HyperspaceTerrainPlugin plugin =
                (HyperspaceTerrainPlugin) Misc.getHyperspaceTerrain().getPlugin();
        NebulaEditor editor = new NebulaEditor(plugin);
        float minRadius = plugin.getTileSize() * 2f;

        float radius = system.getMaxRadiusInHyperspace();
        editor.clearArc(system.getLocation().x, system.getLocation().y, 0,
                radius + minRadius * 0.5f, 0, 360f);
        editor.clearArc(system.getLocation().x, system.getLocation().y, 0,
                radius + minRadius, 0, 360f, 0.25f);
    }
}
