package data.scripts.world.systems;

import com.fs.starfarer.api.Global;
import com.fs.starfarer.api.campaign.JumpPointAPI;
import com.fs.starfarer.api.campaign.LocationAPI;
import com.fs.starfarer.api.campaign.OrbitAPI;
import com.fs.starfarer.api.campaign.PlanetAPI;
import com.fs.starfarer.api.campaign.SectorAPI;
import com.fs.starfarer.api.campaign.SectorEntityToken;
import com.fs.starfarer.api.campaign.StarSystemAPI;
import com.fs.starfarer.api.campaign.econ.MarketAPI;
import com.fs.starfarer.api.impl.campaign.ids.Entities;
import com.fs.starfarer.api.impl.campaign.ids.Factions;
import com.fs.starfarer.api.impl.campaign.ids.Industries;
import com.fs.starfarer.api.impl.campaign.ids.StarTypes;
import com.fs.starfarer.api.impl.campaign.ids.Terrain;
import com.fs.starfarer.api.impl.campaign.procgen.NebulaEditor;
import com.fs.starfarer.api.impl.campaign.procgen.ProcgenUsedNames;
import com.fs.starfarer.api.impl.campaign.procgen.StarAge;
import com.fs.starfarer.api.impl.campaign.terrain.HyperspaceTerrainPlugin;
import com.fs.starfarer.api.util.Misc;
import data.scripts.HyperionRandomizer;
import data.scripts.world.HS_AutoGeneratePlanets;
import data.scripts.world.HS_JumpZoneHabitables;
import java.awt.Color;
import java.util.Random;

/**
 *
 * @author NinjaSiren
 */
public class HS_Klat {
    
    // Roll the dice
    private double rand() {
        Random rand = new Random();
        final double max = 1.0;
        final double min = 0.0;
        return min + rand.nextDouble() * (max - min);
    }
    
    // Roll the dice for planet tariff
    private float tariff() {
        Random rand = new Random();
        final float max = 0.12f;
        final float min = 0.0f;
        return min + rand.nextFloat() * (max - min);
    }
    
    // Roll the dice, system background
    private int rand_bg() {
        Random rand = new Random();
        final int max = 6;
        final int min = 1;
        return min + rand.nextInt(max - min + 1);
    }
    
    public void generate(SectorAPI sector) {
        
        // Add star system
        StarSystemAPI system = sector.createStarSystem("Klat-Perseus");
        LocationAPI hyper = Global.getSector().getHyperspace();
        system.getLocation().set(-9750, 24500);
        system.setBackgroundTextureFilename("graphics/backgrounds/background" + rand_bg() + ".jpg");
        ProcgenUsedNames.notifyUsed("Klat");
        ProcgenUsedNames.notifyUsed("Perseus"); 
        
        // Add stars, Klat
        PlanetAPI klat = system.initStar(
                    "klat", // unique id for this star
                    StarTypes.BLUE_GIANT,  // id in planets.json
                    1250,           // radius (in pixels at default zoom)
                    2450,            // corona radius, from star edge
                    2,             // solar wind burn level
                    0.475f,           // flare probability
                    2.4f);          // CR loss multipiers
        klat.setCustomDescriptionId("hs_star_klat"); 
        klat.setName("Klat");
        
        // Perseus
        PlanetAPI perseus = system.addPlanet(
                    "perseus", // Unique id for this planet (or null to have it be autogenerated)
                    klat, // What the planet orbits (planets is always circular)
                    "Perseus", // Name of the fake star
                    StarTypes.RED_DWARF, // Planet type id in planets.json
                    180, // Starting angle in planets, i.e. 0 = to the right of the star
                    600, // Planet radius, pixels at default zoom
                    klat.getRadius() * 10f, // Orbit radius, pixels at default zoom
                    730); // Days it takes to complete an planets. 1 day = 10 seconds.
        perseus.setCustomDescriptionId("hs_star_perseus");
        
        perseus.getSpec().setCoronaSize(975);
        perseus.getSpec().setCoronaTexture(Terrain.CORONA);
        perseus.applySpecChanges();
        
        // Adds a corona for Perseus
        system.addCorona(
                perseus, // ID or name of the fake star
                Terrain.CORONA, // What terrain type is it, terrain.json
                975, // Additional radius of the terrain type
                1.75f, // The wind burn level of the terrain type
                1.2f, // The flare probability of the terrain type
                1.3f); // The CR loss multiplier of the terrain type 
        
        // Autogenerate planets
        int klat_Amount = 6; // Amount of planets you want
        int perseus_Amount = 2; // Amount of planets you want
        int starsAmount = 2; // The amount of stars you manually added
        
        PlanetAPI[] klat_planets = new PlanetAPI[klat_Amount]; // Initiates the Planet array
        PlanetAPI[] perseus_planets = new PlanetAPI[klat_Amount]; // Initiates the Planet array
        
        PlanetAPI[] stars = new PlanetAPI[starsAmount]; // Initiates the Star array
        stars[0] = klat; // Sets the final values of the Star array
        stars[1] = perseus; // Sets Perseus as a fake star
        
        MarketAPI[] klat_markets = new MarketAPI[klat_Amount]; // Initiates the Market array
        MarketAPI[] perseus_markets = new MarketAPI[klat_Amount]; // Initiates the Market array
        
        SectorEntityToken[] stations = new SectorEntityToken[klat_Amount]; // Initiates the SectorEntityToken array
        
        // Automatically generates random planets in the system based on the values you added
        new HS_AutoGeneratePlanets(
                system,          // The system that will have the auto-generated planets
                klat,            // The star that the planets will orbit on
                null,      // Use this if the center is a the middle of both
                klat_planets,         // The PlanetAPI array where the planets will be stored
                klat_Amount,    // How many planets you want to auto-generate in the system
                stars,           // The PlanetAPI array where the stars are stored
                starsAmount,     // The amount of stars in your system
                klat.getRadius() * 1.5f, // Starting orbit of the planets
                60, // Starting orbital period of the planets
                875,  // Minimum orbit distance between the auto-generated planets
                1500,  // Maximum orbit distance between the auto-generated planets
                0.2f,  // Minimum orbital period of the planets that will be added, min 0.0f max 1.0f
                0.7f,  // Maximum orbital period of the planets that will be added, max 1.0f
                true,            // If true, the system will auto-generate planets
                stations,            // SectorEntityToken array, where the nexrelin stations will be stored
                klat_markets,         // MarketAPI array where all the planet markets will be stored
                Factions.PERSEAN, // The first faction that will be auto-generated on the system
                Factions.REMNANTS,  // The second faction that will be auto-generated on the system
                62.5);  // The percentage of factionA appearing vs factionB on the system, min=0 max=100
        
        new HS_AutoGeneratePlanets(
                system,          // The system that will have the auto-generated planets
                perseus,            // The star that the planets will orbit on
                null,      // Use this if the center is a the middle of both
                perseus_planets,         // The PlanetAPI array where the planets will be stored
                perseus_Amount,    // How many planets you want to auto-generate in the system
                stars,           // The PlanetAPI array where the stars are stored
                starsAmount,     // The amount of stars in your system
                perseus.getRadius() * 1.5f, // Starting orbit of the planets
                60, // Starting orbital period of the planets
                875,  // Minimum orbit distance between the auto-generated planets
                1250,  // Maximum orbit distance between the auto-generated planets
                0.2f,  // Minimum orbital period of the planets that will be added, min 0.0f max 1.0f
                0.7f,  // Maximum orbital period of the planets that will be added, max 1.0f
                true,            // If true, the system will auto-generate planets
                stations,            // SectorEntityToken array, where the nexrelin stations will be stored
                perseus_markets,         // MarketAPI array where all the planet markets will be stored
                Factions.PERSEAN, // The first faction that will be auto-generated on the system
                Factions.REMNANTS,  // The second faction that will be auto-generated on the system
                62.5);  // The percentage of factionA appearing vs factionB on the system, min=0 max=100
        
        // Jump points, Habitable
        JumpPointAPI[] hab_klat_jp = new JumpPointAPI[klat_Amount]; // JumpPointAPI array
        new HS_JumpZoneHabitables(
                hab_klat_jp,         // The JumpPointAPI array where all the jump points are stored
                klat_Amount,   // How many planets that the system has
                klat_planets,        // The PlanetAPI array where the planets will be stored
                klat,           // The star that the jump points will orbit on
                system);        // The system that will have the auto-generated jump points
        
        JumpPointAPI[] hab_perseus_jp = new JumpPointAPI[perseus_Amount]; // JumpPointAPI array
        new HS_JumpZoneHabitables(
                hab_perseus_jp,         // The JumpPointAPI array where all the jump points are stored
                perseus_Amount,   // How many planets that the system has
                perseus_planets,        // The PlanetAPI array where the planets will be stored
                perseus,           // The star that the jump points will orbit on
                system);        // The system that will have the auto-generated jump points
        
        // Jump point orbits
        float orbitJP1 = klat_planets[0].getCircularOrbitRadius() + ((
                klat_planets[1].getCircularOrbitRadius() - klat_planets[0].getCircularOrbitRadius()) / 2);
        float orbitJP2 = klat_planets[3].getCircularOrbitRadius() + ((
                klat_planets[4].getCircularOrbitRadius() - klat_planets[3].getCircularOrbitRadius()) / 2);
        float orbitJP3 = perseus_planets[0].getCircularOrbitRadius() + ((
                perseus_planets[1].getCircularOrbitRadius() - perseus_planets[0].getCircularOrbitRadius()) / 2);
        
        // Jump points, inner
        JumpPointAPI inner_jp = Global.getFactory().createJumpPoint(
                "inner_jp", "Klat Inner Jump Point");
        OrbitAPI orbit_1 = Global.getFactory().createCircularOrbit(
                klat, 
                klat_planets[0].getCircularOrbitAngle() * 1.5f, 
                orbitJP1, 
                klat_planets[0].getCircularOrbitPeriod() * 1.5f);
        inner_jp.setOrbit(orbit_1);
        inner_jp.setStandardWormholeToHyperspaceVisual();
        system.addEntity(inner_jp);
        
        // Jump points, outer
        JumpPointAPI outer_jp = Global.getFactory().createJumpPoint(
                "outer_jp", "Klat Inner Jump Point");
        OrbitAPI orbit_2 = Global.getFactory().createCircularOrbit(
                klat, 
                klat_planets[3].getCircularOrbitAngle() * 1.5f, 
                orbitJP2, 
                klat_planets[3].getCircularOrbitPeriod() * 1.5f);
        outer_jp.setOrbit(orbit_2);
        outer_jp.setStandardWormholeToHyperspaceVisual();
        system.addEntity(outer_jp);
        
        // Jump points, perseus
        JumpPointAPI perseus_jp = Global.getFactory().createJumpPoint(
                "perseus_jp", "Perseus Jump Point");
        OrbitAPI orbit_3 = Global.getFactory().createCircularOrbit(
                perseus, 
                perseus_planets[0].getCircularOrbitAngle() * 1.5f, 
                orbitJP3, 
                perseus_planets[0].getCircularOrbitPeriod() * 1.5f);
        perseus_jp.setOrbit(orbit_3);
        perseus_jp.setStandardWormholeToHyperspaceVisual();
        system.addEntity(perseus_jp);
        
        // Autogenerated jump points
        system.autogenerateHyperspaceJumpPoints(true, true);
                
        // Specials orbits
        float orbitNB = klat_planets[1].getCircularOrbitRadius() - ((
                klat_planets[2].getCircularOrbitRadius() - klat_planets[1].getCircularOrbitRadius()) / 2);
        float orbitCR = perseus_planets[0].getCircularOrbitRadius() + ((
                perseus_planets[1].getCircularOrbitRadius() - perseus_planets[0].getCircularOrbitRadius()) / 2);
        float orbitSA = klat_planets[3].getCircularOrbitRadius() - ((
                klat_planets[4].getCircularOrbitRadius() - klat_planets[3].getCircularOrbitRadius()) / 2);
        
        //Nav Buoy
        SectorEntityToken nav_buoy = system.addCustomEntity(
                "klat_navbuoy",
                "Klat Nav Buoy",
                Entities.NAV_BUOY,
                Factions.PERSEAN);
        nav_buoy.setCircularOrbit(
                klat, 
                klat_planets[1].getCircularOrbitAngle() * 1.5f, 
                orbitNB, 
                klat_planets[1].getCircularOrbitPeriod() * 1.5f);

        //Comm Relay
        SectorEntityToken comm_relay = system.addCustomEntity(
                "perseus_commrelay",
                "Perseus Relay",
                Entities.COMM_RELAY,
                Factions.PERSEAN);
        comm_relay.setCircularOrbit(
                perseus, 
                (perseus_planets[0].getCircularOrbitAngle() * 1.5f) - 180, 
                orbitCR, 
                perseus_planets[0].getCircularOrbitPeriod() * 1.5f);

        //Sensor Array
        SectorEntityToken sensor_array = system.addCustomEntity(
                "klat_sensorarray",
                "Klat Sensor Array",
                Entities.SENSOR_ARRAY,
                Factions.PERSEAN);
        sensor_array.setCircularOrbit(
                klat, 
                klat_planets[3].getCircularOrbitAngle() * 1.5f, 
                orbitSA, 
                klat_planets[3].getCircularOrbitPeriod() * 1.5f);
        
        // Cleaning the hyperspace
        HyperspaceTerrainPlugin plugin =
                (HyperspaceTerrainPlugin) Misc.getHyperspaceTerrain().getPlugin();
        NebulaEditor editor = new NebulaEditor(plugin);
        float minRadius = plugin.getTileSize() * 2f;

        float radius = system.getMaxRadiusInHyperspace();
        editor.clearArc(system.getLocation().x, system.getLocation().y, 0,
                radius + minRadius * 0.5f, 0, 360f);
        editor.clearArc(system.getLocation().x, system.getLocation().y, 0,
                radius + minRadius, 0, 360f, 0.25f);
        
        // Other system automation stuff
        system.setStar(klat);
        system.setSecondary(perseus);
        system.setAge(StarAge.YOUNG);
        system.setHasSystemwideNebula(true);
    }
    
    // Extra industry randomizer
    private String cryoIndustries() {
        double random = rand();
        
        if(random <= 0.8) {
            return null;
        } else if(random > 0.8 && random >= 0.9) {
            return Industries.CRYOSANCTUM;
        } else {
            return "cryorevival";
        }
    }
    
    // Ship Hull Randomizers
    private String HSSship_id() {
        int number = new HyperionRandomizer(11).value;
        String ship_id;

        //Ship Randomizers
        switch (number) {
            case 0:
                return ship_id = "HS_Orionis";
            case 1:
                return ship_id = "HS_Naos";
            case 2:
                return ship_id = "HS_Betelgeuse";
            case 3:
                return ship_id = "HS_Arcturus";
            case 4:
                return ship_id = "HS_Icarus";
            case 5:
                return ship_id = "HS_Alycone";
            case 6:
                return ship_id = "HS_Bellatrix";
            case 7:
                return ship_id = "HS_Carinae";
            case 8:
                return ship_id = "HS_Sirius";
            case 9:
                return ship_id = "HS_Eridani";
            case 10:
                return ship_id = "HS_Cassiopeia";
            case 11:
                return ship_id = "HS_Perseus";
            default:
                break;
        }
        return null;
    }
    
    private String HCOship_id() {
        int number = new HyperionRandomizer(12).value;
        String ship_id;

        //Ship Randomizers
        switch (number) {
            case 0:
                return ship_id = "HS_Orionis_Confederacy";
            case 1:
                return ship_id = "HS_Naos_Confederacy";
            case 2:
                return ship_id = "HS_Atlas_Confederacy";
            case 3:
                return ship_id = "HS_Buffalo_Confederacy";
            case 4:
                return ship_id = "HS_Gemini_Confederacy";
            case 5:
                return ship_id = "HS_Alycone_Confederacy";
            case 6:
                return ship_id = "HS_Bellatrix_Confederacy";
            case 7:
                return ship_id = "HS_Carinae_Confederacy";
            case 8:
                return ship_id = "HS_Sirius_Confederacy";
            case 9:
                return ship_id = "HS_Eridani_Confederacy";
            case 10:
                return ship_id = "HS_Cassiopeia_Confederacy";
            case 11:
                return ship_id = "HS_Perseus_Confederacy";
            case 12:
                return ship_id = "HS_Valkyrie_Confederacy";
            default:
                break;
        }
        return null;
    }
}
